---
%{kind_service}
metadata:
  labels:
    app: %{application}-%{environment}-svc
  name: %{application}-%{environment}-svc
  namespace: %{project}-%{environment}
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: %{nodeport}
    protocol: TCP
  selector:
    app: nginx
