---
%{kind_deployment}
%{metadata_nginx}
spec:
  %{deployment_strategy}
  replicas: %{pod_replicas}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - image: nginx:%{nx_tag}
        imagePullPolicy: Always
        name: %{application}
        resources:
         limits:
           cpu: %{cpu_limits}
           memory: %{memory_limits}
         requests:
           cpu: %{cpu_requests}
           memory: %{memory_requests}
        ports:
        - containerPort: 80
          name: web
